force-app/main/default/objects/GICModel__c/GICModel__c.object-meta.xml
<CustomObject>
    <label>GICModel</label>
    <nameField>
        <label>GICModel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GICModels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GICModel__c/fields/cloudId__c.field-meta.xml
<CustomField>
    <fullName>cloudId__c</fullName>
    <label>cloudId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GICModel__c/fields/modelId__c.field-meta.xml
<CustomField>
    <fullName>modelId__c</fullName>
    <label>modelId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GICModel__c/fields/projectId__c.field-meta.xml
<CustomField>
    <fullName>projectId__c</fullName>
    <label>projectId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GICZone__c/GICZone__c.object-meta.xml
<CustomObject>
    <label>GICZone</label>
    <nameField>
        <label>GICZone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GICZones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GICZone__c/fields/GICModel__c.field-meta.xml
<CustomField>
    <fullName>GICModel__c</fullName>
    <label>GICModel</label>
    <referenceTo>GICModel__c</referenceTo>
    <relationshipLabel>GICZones</relationshipLabel>
    <relationshipName>GICZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GICZone__c/fields/uuid__c.field-meta.xml
<CustomField>
    <fullName>uuid__c</fullName>
    <label>uuid</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GICModelUtil.cls
public with sharing class GICModelUtil {
    public static GICModel__c find(Id gicModelId){
        return [SELECT 
                Id,
                cloudId__c,
                projectId__c,
                modelId__c,
                Name
            FROM 
            GICModel__c 
            WHERE Id = :gicModelId
        ];
    }

    @future(callout=true)
    public static void loadZones(Id gicModelId){
        GICModel__c currentGICModel = GICModelUtil.find(gicModelId);

        BimdataApi api = BIMDataAPI.new_session();
        api.cloudId = currentGICModel.cloudId__c;
        api.projectId = currentGICModel.projectId__c;
        api.modelId = currentGICModel.modelId__c;
        List<Map<String,Object>> zones = api.getZones();
        List<GICZone__c> gicZones = new List<GICZone__c>();
        for(Map<String,Object> zone : zones){
            GICZone__c gicZone = new GICZone__c();
            gicZone.GICModel__c = currentGICModel.Id;
            gicZone.Name = (String)zone.get('name');
            gicZone.uuid__c = (String)zone.get('uuid');
            gicZones.add(gicZone);
        }
        insert gicZones;
    }
}