force-app/main/default/objects/GICModel__c/GICModel__c.object-meta.xml
<CustomObject>
    <label>GICModel</label>
    <nameField>
        <label>GICModel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GICModels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GICModel__c/fields/cloudId__c.field-meta.xml
<CustomField>
    <fullName>cloudId__c</fullName>
    <label>cloudId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GICModel__c/fields/modelId__c.field-meta.xml
<CustomField>
    <fullName>modelId__c</fullName>
    <label>modelId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GICModel__c/fields/projectId__c.field-meta.xml
<CustomField>
    <fullName>projectId__c</fullName>
    <label>projectId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BIMDataViewerController.cls
global with sharing class BIMDataViewerController {
  public String cloudId {get; set;}
  public String projectId {get; set;}
  public String modelId {get; set;}
  public String viewerToken {get; set;}

  private String getViewerToken() {
    BIMDataAPI api = BIMDataAPI.new_session();
    api.cloudId = cloudId;
    api.projectId = projectId;
    return api.createProjectToken();
  }
  
  public BIMDataViewerController() {
    String recordId = ApexPages.currentPage().getParameters().get('id').escapeHtml4();
    GICModel__c gicModel =  GICModelUtil.find(recordId);

    BIMDataAPI api = BIMDataAPI.new_session();
    cloudId = gicModel.cloudId__c;
    projectId = gicModel.projectId__c;
    modelId = gicModel.modelId__c;
    viewerToken = getViewerToken();
  }
}