force-app/main/default/objects/GICAnnotation__c/GICAnnotation__c.object-meta.xml
<CustomObject>
    <label>GICAnnotation</label>
    <nameField>
        <label>GICAnnotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GICAnnotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GICAnnotation__c/fields/color__c.field-meta.xml
<CustomField>
    <fullName>color__c</fullName>
    <label>color</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GICAnnotation__c/fields/GICModel__c.field-meta.xml
<CustomField>
    <fullName>GICModel__c</fullName>
    <label>GICModel</label>
    <referenceTo>GICModel__c</referenceTo>
    <relationshipLabel>GICAnnotations</relationshipLabel>
    <relationshipName>GICAnnotations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GICAnnotation__c/fields/GICZone__c.field-meta.xml
<CustomField>
    <fullName>GICZone__c</fullName>
    <label>GICZone</label>
    <referenceTo>GICZone__c</referenceTo>
    <relationshipLabel>GICAnnotations</relationshipLabel>
    <relationshipName>GICAnnotations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GICAnnotation__c/fields/x__c.field-meta.xml
<CustomField>
    <fullName>x__c</fullName>
    <label>x</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GICAnnotation__c/fields/y__c.field-meta.xml
<CustomField>
    <fullName>y__c</fullName>
    <label>y</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GICAnnotation__c/fields/z__c.field-meta.xml
<CustomField>
    <fullName>z__c</fullName>
    <label>z</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GICModel__c/GICModel__c.object-meta.xml
<CustomObject>
    <label>GICModel</label>
    <nameField>
        <label>GICModel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GICModels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GICZone__c/GICZone__c.object-meta.xml
<CustomObject>
    <label>GICZone</label>
    <nameField>
        <label>GICZone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GICZones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GICZone__c/fields/GICModel__c.field-meta.xml
<CustomField>
    <fullName>GICModel__c</fullName>
    <label>GICModel</label>
    <referenceTo>GICModel__c</referenceTo>
    <relationshipLabel>GICZones</relationshipLabel>
    <relationshipName>GICZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GICAnnotationUtil.cls
public with sharing class GICAnnotationUtil {
    static public List<GICAnnotation__c> whereInZone(Id gicZoneId){
        return [SELECT
            Id,
            GICModel__c,
            GICZone__c,
            Name,
            x__c,
            y__c,
            z__c,
            color__c
            FROM
                GICAnnotation__c
            WHERE
                GICZone__c = :gicZoneId                 
        ];
    }

    static public GICAnnotation__c find(Id gicAnnotationId){
        return [SELECT
            Id,
            GICModel__c,
            GICZone__c,
            Name,
            x__c,
            y__c,
            z__c,
            color__c
            FROM
                GICAnnotation__c
            WHERE
                Id = :gicAnnotationId                 
        ];
    }

    static public GICAnnotation__c create(
        String zoneId,
        String name,
        String x,
        String y,
        String z,
        String color
    ){
        GICZone__c zone = GICZoneUtil.find(zoneId);
        GICAnnotation__c gicAnnotation = new GICAnnotation__c(
            GICModel__c = zone.GICModel__c,
            GICZone__c = zoneId,
            Name = name,
            x__c = Decimal.valueOf(x),
            y__c = Decimal.valueOf(y),
            z__c = Decimal.valueOf(z),
            color__c = color
        );
        insert gicAnnotation;
        return find(gicAnnotation.Id);
    }

    public static List<Map<String, Object>> toMap(List<GICAnnotation__c> gicAnnotations){
        List<Map<String, Object>> annotationsMap = new List<Map<String, Object>>();
        for(GICAnnotation__c annotation : gicAnnotations){            
            Map<String, Object> annotationMap = new Map<String, Object>{
                'id' => annotation.Id,
                'name' => annotation.name,
                'x' => annotation.X__c,
                'y' => annotation.Y__c,
                'z' => annotation.Z__c,
                'color' => annotation.color__c
            };
            annotationsMap.add(annotationMap);

        }
        return annotationsMap;
    }

}